config/routes.rb
IrcArch::Application.routes.draw do
  resources :messages
  match 'search' => 'search#search'
  root :to => 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  def self.upper_context(m, num_msgs = 5)
    start_id = m.id - num_msgs
    if (start_id < 0)
      start_id = 0
    end
    find_by_sql(["select t.* from messages t where t.id > #{start_id} and t.id < #{m.id} order by t.created_at desc limit #{num_msgs}"])
  end
  
  def self.lower_context(m, num_msgs = 5)
    end_id = m.id + num_msgs
    find_by_sql(["select t.* from messages t where t.id > #{m.id} and t.id < #{end_id} order by t.created_at desc limit #{num_msgs}"])
  end
  
  def self.search(terms)
    find_by_sql(["select t.* from messages t where #{ (["(lower(t.body) like ? or lower(t.author) like ?)"] * terms.size).join(" or ") } order by t.created_at desc", *(terms * 2).sort])
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :message

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @search_res = []
    @search_terms = []
    @performed_search = false
    if params.has_key?(:search_terms) && !params[:search_terms].empty?
      @performed_search = true
      @search_terms = params[:search_terms].split
      @search_res = Message.search(@search_terms.collect{ |c| "%#{c.downcase}%" })
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def mark_terms(str, terms)
    if str.nil?
      return str
    end
    rv = str
    terms.each { |t|
      rv = rv.gsub(/#{t}/i, "<span class=\"search_term\">\\0</span>")
    }
    return rv
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Archaic</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  <%= yield :javascripts %>
</head>
<body>
  <div>
    <div>
      <a href="<%= root_path %>"><img src="/images/old-books-cropped.png" style="height: 120px; float: left;"/></a>
      <div style="float: left; margin-top: 40px; margin-left: 10px;">
        <div style="font-size: 30px; font-weight: bold;">Archaic</div>
        <div style="font-size: 10px; color: #999;">Archiving history in the most useful of ways</div>
      </div>
      <div style="float: right; margin-top: 40px;">
        <%= form_tag(search_path) do -%>
          <div style="float: right;">
            <%= text_field_tag 'search_terms', nil, :size => 30 %>
            <%= submit_tag 'Search' %>
          </div>
          <div style="clear: both;"></div>
        <% end -%>
        <%= link_to 'Messages', messages_path, :style => "margin-top: 5px;" %>
      </div>
      <div style="clear: both;"></div>
    </div>
  </div>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Messages</h1>

<%= render :partial => "shared/message", :collection => @messages %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>

<p>
  <b>Author:</b>
  <%= @message.author %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/search/search.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag("jquery-1.4.4.min") %>
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
      $(".match_container").toggle(function() {
        $(this).find('.message_upper_context').show();
        $(this).find('.message_lower_context').show();
      }, function() {
        $(this).find('.message_upper_context').hide();
        $(this).find('.message_lower_context').hide();
      });
    });
  </script>
<% end %>

<% if @performed_search %>
  <% if @search_res.empty? %>
    <h2>No matches found for <%= @search_terms.join(", ") %></h2>
  <% elsif @search_res.size == 1 %>
    <h2><%= @search_res.size %> match found for <%= @search_terms.join(", ") %></h2>
  <% elsif @search_res.size > 1 %>
    <h2><%= @search_res.size %> matches found for <%= @search_terms.join(", ") %></h2>
  <% end %>

  <% @search_res.each do |m| %>
    <div class="match_container">
      <div class="message_upper_context">
        <% Message.upper_context(m).each do |cm| %>
          <%= render :partial => "shared/custom_message", :locals => { :author => raw(cm.author), :body => raw(cm.body), :created_at => cm.created_at } %>
        <% end %>
      </div>
      <%= render :partial => "shared/custom_message", :locals => { :author => raw(mark_terms(m.author, @search_terms)), :body => raw(mark_terms(m.body, @search_terms)), :created_at => m.created_at } %>
      <div class="message_lower_context">
        <% Message.lower_context(m).each do |cm| %>
          <%= render :partial => "shared/custom_message", :locals => { :author => raw(cm.author), :body => raw(cm.body), :created_at => cm.created_at } %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_custom_message.html.erb
<div class="message">
  <div class="message_created_at"><%= time_ago_in_words(created_at) %></div>
  <div class="message_author"><%= author %></div>
  <div class="message_body"><%= body %></div>
</div>
<div style="clear: both;"></div>

app/views/shared/_message.html.erb
<div class="message">
  <div class="message_created_at"><%= time_ago_in_words(message.created_at) %></div>
  <div class="message_author"><%= message.author %></div>
  <div class="message_body"><%= message.body %></div>
  <div style="clear: both;"></div>
</div>